### ISSUE TITLE
What does the seventh column of the inputted file represent?

### ISSUE THREAD

**Issue by kuangzhuoran** [adadiehl/mapLoopLoci#1]
The first six columns represent the genomic positions, the eighth column should be the interaction counts, and the ninth column represents the p-values。
I don't quite understand the meaning of the seventh column.

what does 99179/ 99186/ 99175 mean
chr22   18312801        18313021        chr22   18558869        18559119        99179   105     0.000000
chr22   18941930        18942280        chr22   19132279        19132487        99186   8       0.032835

**Comment by kuangzhuoran** [comment]
Another question is, I'm wondering if the first three columns are the target or if it's the fourth to sixth columns? Taking ’example_data‘ as an example, is ‘example_loop_data.hg19.GM12878.bedpe’ the target?

**Comment by adadiehl** [comment]
Greetings,

The example data files follow bedpe conventions. You are correct that the
first six columns represent loop anchor loci: columns 1-3 represent the
first loop anchor and 4-6 represent the second anchor. The seventh column
is the name column, and contains a unique identifier for each loop.

To expand more on terminology, I'm using 'query' and 'target' to
differentiate between the two sets of loops used in a comparison. The query
is the first sample in the comparison. All the loops in this sample are
compared to loops in the query set, and will be labelled with their
conservation class in the output.

Hope this helps!

Best,
Adam Diehl

**Comment by kuangzhuoran** [comment]
Thanks for your help !
