### ISSUE TITLE
How to cite this tools “mapLoopLoci” ?

### ISSUE THREAD

**Issue by kuangzhuoran** [adadiehl/mapLoopLoci#2]
Is it okay if I just cite this website: "https://github.com/adadiehl/mapLoopLoci"?

**Comment by adadiehl** [comment]
The correct citation for MapLoopLoci is:
*Transposable elements contribute to cell and species-specific chromatin
looping and gene regulation in mammalian genomes.*
*Diehl AG*, *Ouyang N*, *Boyle AP*. *Nature Communications* 2020, 11:1796.
PMID: 32286261.

**Comment by kuangzhuoran** [comment]
Get it. Thank you~
